### ISSUE TITLE
Fix the last line in multiplication table

### ISSUE THREAD

**Issue by asarfraaz** [Louis-Sunil/python_exercises#1]
https://github.com/Louis-Sunil/python_exercises/blob/67397f44d9b0f1b0077a17e0d43272f78540c458/Multiplication_Table_17.py#L1

The output of this program I got was :
$ python Multiplication_Table_17.py 
17 * 1 = 17
17 * 2 = 34
17 * 3 = 51
17 * 4 = 68
17 * 5 = 85
17 * 6 = 102
17 * 7 = 119
17 * 8 = 136
17 * 9 = 153
17 * 10 = 170
$

All the '=' symbols are aligned one below the other, except the last one
Can we re-align all the '=' symbols, such that they are exactly below each other for all the 10 lines?

**Comment by Louis-Sunil** [comment]
Corrected the program as per the above comments for table 17
I have used space followed by tab in print command " \t="
